### ISSUE TITLE
Could I run it in mobile device?

### ISSUE THREAD

**Issue by tomtomtong** [Kariaro/VRigUnity#4]
Great repo. Could I run it in mobile device?

**Comment by Kariaro** [comment]
If you are asking for permission then sure. Just link my alias or give creds in a readme :D Otherwise…

I’ve never developed a mobile application before using Unity so I don’t know if this project would work without modifications.

To make it work on mobile the Mediapipe libraries would need to be built for iOS, Android. 👍

**Comment by tomtomtong** [comment]
Thank for your great work.
I will publish the application here.
https://vtubershop.booth.pm/items/4275972

**Comment by tomtomtong** [comment]
Thank for your great work.
I will publish the application here.
https://vtubershop.booth.pm/items/4275972
